### ISSUE TITLE
Using the library causes an error to occur

### ISSUE THREAD

**Issue by sethsnel** [bence-toth/react-hook-geolocation#38]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/3225809/142769132-024c2a56-34d8-49ca-b065-4d215a28da52.png">

I use the library in a project in combination with:
- Typescript
- NextJs

I import the module like this:

`import useGeolocation from 'react-hook-geolocation'`

Am I doing something wrong?

**Comment by bence-toth** [comment]
Hi @sethsnel, thank you for reporting it. I just published a new version recently, maybe something went wrong. I'll look into it soon, in the meantime please try installing an earlier version.

**Comment by bence-toth** [comment]
Hi again @sethsnel, I'd like to hear a bit more about your use case, I just tried to reproduce the issue and I couldn't. I set up a new app using Create React App, installed the package, and copied the example in the `README.md` file. It seems to be working fine for me.

When doing the same using the default TS template for CRA, I see that it complains that type declarations are not available, which I am afraid is the case. I could make it work importing it like this:

```js
const { default: useGeolocation } = require("react-hook-geolocation");
```

Let me know if this helps.

**Comment by bence-toth** [comment]
Hi again @sethsnel,

I just published a new version `1.0.11` which also includes the ambient types for the package.

If you update your project to that version, importing the way you did it (`import useGeolocation from 'react-hook-geolocation'`) should work just fine.

**Comment by sethsnel** [comment]
Thanks for the quick response, I only have this issue with this package. Other packages give no issue.
For now I've copied the useGeolocation file to my local repo, which is sufficient for my use-case at the moment. But of course I would lose package management and updates. Even upgrading to `1.0.11` does not fix the issue.

Importing like:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/3225809/142773141-6da35a8a-83c7-4633-befe-166983eb1751.png">

Reproducing setting up project:
https://nextjs.org/docs/api-reference/create-next-app
`yarn create next-app --typescript`
`yarn add react-hook-geolocation`

And then use it in a page for example.
<img width="278" alt="image" src="https://user-images.githubusercontent.com/3225809/142773184-94ef7aeb-52b2-47be-ad9f-f673bfb5be7f.png">

**Comment by bence-toth** [comment]
Hi again @sethsnel 

I reproduced your issue. I'm afraid I'm not familiar with Next.JS, but I was digging around a little, and to me it looks like that this is actually a problem with many modules when NextJS tries to do the server-side rendering and they are components/hooks that rely on being rendered in the browser.

There's a way around this documented in NextJS docs which consists on using a dynamic import disabling server-side rendering:

```
import dynamic from 'next/dynamic'

const ClientSideComponent = dynamic(import('client-side-component'), { ssr: false }) // Geolocation cannot be server-side rendered

export const App = () => {
    return <ClientSideComponent {...} />
}
```

However, this only works with Components, and not custom hooks.

I found a conversation about a similar issue here, this might help: https://github.com/vercel/next.js/discussions/16987

**Comment by sethsnel** [comment]
Well it does make sense that the geolocation api can only be used within a browser content. Perhaps add logic to verify `if(!window) { console.warn('useGeolocation should only be used in the client'); return; }`.

I think that importing could be possible.
And also, copy pasting the the file to my repo also seems to work fine. (see referenced project on GitHub).

Thanks anyway for diving into it!
